### ISSUE TITLE
Use of Entity Framework 2nd Level Cache causes exception on TransformCommand: QueryableValues only works with a SQL Server provider

### ISSUE THREAD

**Issue by micheloliveira-com** [yv989c/BlazarTech.QueryableValues.EF6#12]
Hi, I'm testing this library with EF 6.4.4 and EFCache.Redis lib (https://github.com/silentbobbert/EFCache.Redis).

After running an optimized query by QueryableValues, an exception is thrown on "QueryableValuesCommandInterceptor" class:
`QueryableValues only works with a SQL Server provider`

This is the type of DbCommand generated by EFCache lib:
`EFCache.CachingCommand`

Can we've an option to disable this check (like XML or JSON processors)?
I solved it by removing this code:
```
            if (command is not SqlCommand sqlCommand)
            {
                throw Util.NewOnlyWorksWithSqlServerException();
            }
```
And added this one instead:
```			DbCommand sqlCommand = command;```

Thanks @yv989c

**Comment by yv989c** [comment]
Hi @michlns,

Can you please try [this pre-release package](https://www.nuget.org/packages/BlazarTech.QueryableValues.EF6.SqlServer/1.1.2-build.41)?

Please let me know if that works. Thanks.

**Comment by micheloliveira-com** [comment]
I tested with pre-realease package and flawless worked here @yv989c .

Thanks.

**Comment by yv989c** [comment]
Hi @michlns,

Version `1.1.2` which contains this fix should deploy to NuGet in a few.

Have a great rest of your weekend! ✌️
