### ISSUE TITLE
ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by micheloliveira-com** [yv989c/BlazarTech.QueryableValues.EF6#9]
Hello.

When EF6 receive this type of query handled by BlazarTech.QueryableValues.EF6, the error "ArgumentException: An item with the same key has already been added." appears:
> `
					query = query
						.GroupBy(x => new { x.a, x.b })
						.OrderByDescending(g => g.Key.b)
						.Select(g => g.FirstOrDefault());
`

The command above duplicates the query, and the TransformCommand method is not validating the dictionary for duplicates:

> `
   at BlazarTech.QueryableValues.QueryableValuesCommandInterceptor.TransformCommand(DbCommand command, DbCommandInterceptionContext interceptionContext)
`

This line at QueryableValues.EF6.SqlServer)/QueryableValuesCommandInterceptor.cs :
> `
                            parameters.Add(valueParameterName, serializationFormat);
`

Must be:
> `
if (!parameters.ContainsKey(valueParameterName))
                            parameters.Add(valueParameterName, serializationFormat);
`

**Comment by yv989c** [comment]
Hi @michlns ! Thanks a lot for your contribution! I'll review this during the weekend.

**Comment by yv989c** [comment]
Hey @michlns!

I just released [`v1.1.1`](https://www.nuget.org/packages/BlazarTech.QueryableValues.EF6.SqlServer) with your fix (#11).

Please let me know if everything is alright on your end with this new release.

Thanks!

**Comment by micheloliveira-com** [comment]
Hello @yv989c, thanks a lot for releasing it.

On my tests, all problems has been solved with v1.1.1 version.
